### ISSUE TITLE
openstack-swift: promisify somehow loose context

### ISSUE THREAD

**Issue by drzraf** [adriantombu/packages#7]
```
swift.getContainer().then(
    c => console.log(c)
);
```

```
(node:47030) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Container' of undefined
    at exports.getContainer (/node_modules/pkgcloud/lib/pkgcloud/openstack/storage/client/containers.js:63:56)
    at Promise (internal/util.js:274:30)
    at new Promise (<anonymous>)
    at internal/util.js:273:12
    at Swift.<anonymous> (/node_modules/@adriantombu/openstack-swift/lib/index.js:128:43)
    at step (/node_modules/@adriantombu/openstack-swift/lib/index.js:52:23)
    at Object.next (/node_modules/@adriantombu/openstack-swift/lib/index.js:33:53)
    at /node_modules/@adriantombu/openstack-swift/lib/index.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/node_modules/@adriantombu/openstack-swift/lib/index.js:23:12)
(node:47030) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Apparently, within https://github.com/pkgcloud/pkgcloud/blob/b6e5b0d4db8d164f444c780ac96c06e555e0b703/lib/pkgcloud/openstack/storage/client/containers.js#L62
`var containerName = container instanceof this.models.Container ? container.name : container,`
`this` is the global object and `this.models` is null.

Note sure whether promisification or transpilation/generators are at cause here (or just pkgcloud@2.2.0).

**Comment by adriantombu** [comment]
Hey @drzraf thanks for taking the time to report this error ! I haven't used this package for a long time but I'll check this out thoroughly next week 😊

**Comment by adriantombu** [comment]
It should be resolved with this commit https://github.com/adriantombu/packages/commit/9f77712b48912c31750de74682a3bdc1a1deaf6f

I made some breaking changes on the way the package is working so i bumped the version to 2.0.0 and updated the readme to get a better documentation :)
